### ISSUE TITLE
Add content to db-maasswaveforms.md

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb-inventory#11]
Add content to or delete  MaassWaveForm(s).md -- one of each!

**Comment by edgarcosta** [comment]
MaassWaveForm deleted.
Still missing the content of MaassWaveForms.md

**Comment by AndrewVSutherland** [comment]
@lemurell, @fredstro The [maasswaveforms](https://github.com/LMFDB/lmfdb-inventory/blob/master/db-MaassWaveForms.md) database still has no documentation.

**Comment by JohnCremona** [comment]
I'm going to close this since now the content should be added at http://beta.lmfdb.org/inventory/
