### ISSUE TITLE
Add content to db-SL2Zsubgroups.md

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb-inventory#12]
db-SL2Zsubgroups.md

**Comment by AndrewVSutherland** [comment]
@sehlen, the [SL2Zsubgroups database](https://github.com/LMFDB/lmfdb-inventory/blob/master/db-SL2Zsubgroups.md) still has no documentation.

**Comment by JohnCremona** [comment]
I'm closing this as now the information should be added at http://beta.lmfdb.org/inventory/
