### ISSUE TITLE
Add content to db-modularforms2.md (classical modular forms)

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb-inventory#13]

**Comment by AndrewVSutherland** [comment]
The inventory for modularforms2 should indicate exactly which collections are actually used by the production system (there are many different incarnations of various collections and it is not clear which are currently used and which are not), and should also make clear exactly which subset of the records in a given collection are used in the current production system (e.g. only those with 'version' = 1.3)

**Comment by JohnCremona** [comment]
+1
Please delete all redundant collections!

**Comment by AndrewVSutherland** [comment]
@sehlen, @fredstro The [modularforms2 database](https://github.com/LMFDB/lmfdb-inventory/blob/master/db-modularforms2.md) still has no documentation.

**Comment by sehlen** [comment]
I know. I'm sorry but I'll be moving from Canada back to Europe next
weekend and won't have much time during the next 2-3 weeks probably.

**Comment by sehlen** [comment]
PS: I started some documentation in my fork on github a while ago (just in
case @fredstro wants to continue it).

**Comment by AndrewVSutherland** [comment]
Thank you @fredstro for filling this in!  Closing.
