### ISSUE TITLE
Add content to db-bmfs.md (Bianchi Modular Forms)

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb-inventory#14]

**Comment by JohnCremona** [comment]
I am closing this since all the data is the dimensions collection is documented, while the forms collection is still empty.

**Comment by AndrewVSutherland** [comment]
Indexes?

**Comment by JohnCremona** [comment]
If I was working on this code then I would care.  As I am not, there are too many other things to do, I am just going to delete this database since if I ever get to work on Bianchi forms again I will just recreate it.
