### ISSUE TITLE
Add documentation for db-transitivegroups.md

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb-inventory#38]

**Comment by AndrewVSutherland** [comment]
The Gmodules collections still needs to be documented, and index information needs to be added for all collections.

**Comment by AndrewVSutherland** [comment]
@jwj61 the Gmodules collections still needs to be documented, and index information needs to be added for both groups and Gmodules.

**Comment by jwj61** [comment]
Done
