### ISSUE TITLE
Add more small groups to sato-tate.smal_groups

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb-inventory#49]
I am making updates to the local fields database/pages.  When an inertia subgroup is not transitive, we will identify the group by gap small group id (rather than the first instance as a transitive subgroup), and am pulling information from the small_groups database.

Currently, the only extra group I need is [324, 164], but adding others is obviously fine too.

On a related note, I plan to make dynamic knowls for these groups.  Is there other data which would be worth adding which is easy to compute?  Maybe conjugacy class data (order of representative and size of class for each class), or list of sizes of normal subgroups?

One motivation for the extra information is that the group mentioned above is isomorphic to C_3^4:C_4, but it is not the wreath product.  So, having more information might help clarify the situation.

**Comment by AndrewVSutherland** [comment]
I can easily add small groups data for all 92804 groups of order less than 512 (there are over 10 million of order 512, so I don't think we want to add those without a compelling reason).  It would be easy to add a list of group ids of maximal and normal subgroups (so just up to isomorphism, not up to conjugacy).

I'm not sure it makes sense to give detailed conjugacy class data, which would be rather more involved (we would need to think about how to label them, and for abelian groups it seems slightly silly), but I could see giving a  summary, say counts of the number of conjugacy classes by sizes and orders.

BTW, for the group [324,164] the group name given by Magma is C3^2:(C3:S3.C2) (which is what I use to generate the "pretty" field), which clearly distinguishes it from the wreath product.

**Comment by jwj61** [comment]
I wondered where you got the pretty names from.  Good to know.

Doing groups of orders < 512 now looks like it makes sense.

I view adding additional information about each group as worthwhile in the long run, but we would probably want input from others first.  By the way, I like your suggestion on maximal and normal subgroups (preferably with multiplicity information).

By the way, for the group I mentioned the clearest picture probably would be C_3^4:C_4 with rational canonical form for the image of a generator of C_4 in Aut(C_3^4) (which turns out to be two blocks of x^2+1).  Obviously, that type of information makes sense because of the structure of this particular group, and is harder to do on a large scale.

**Comment by AndrewVSutherland** [comment]
Yes, I agree normal and maximal subgroup ids should be recorded with multiplicity.  I could also see adding the commutator subgroup (and corresponding abelian quotient), along with the center.

I have a magma script that generates the data that gets loaded into the small groups collection, so it is easy to add invariants as we think of them, we don't need to agree on a "complete" set now (as long as we are restricting to orders < 512, regenerating and reloading the collection is easy).

But I'll hold off for the moment in case anyone else wants to chime in.

**Comment by AndrewVSutherland** [comment]
Small groups data for groups of order < 512 is now available on beta, including the group [324,164], see
http://beta.lmfdb.org/api/sato_tate_groups/small_groups/?label=324.164.

I added conjugacy class summary info, information on maximal/normal subgroups, as well as the center, derived group, and maximal abelian quotient (I'll update the inventory doc to reflect this shortly).

Let me know if/when you are happy with this and I will propagate it to the production database in the cloud.

**Comment by jwj61** [comment]
Looks great.

**Comment by AndrewVSutherland** [comment]
OK, the data is now on the cloud, see http://www.lmfdb.org/api/sato_tate_groups/small_groups/?label=324.164, for example.
