### ISSUE TITLE
pull request for local fields

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb-inventory#50]
Please upload newfields and newfields.rand to the cloud.  There were errors when generating labels of some of the new entries, now fixed.

**Comment by AndrewVSutherland** [comment]
Done.  Let me know if the data looks good and I will then delete the old versions.

**Comment by jwj61** [comment]
It may be a while.  The changes are not visible until the supporting code makes its way to the production server.

**Comment by AndrewVSutherland** [comment]
No rush.

**Comment by jwj61** [comment]
Ready for the next step: please copy fields and fields.rand from localfields to the cloud.  The cloud version of the code does not currently access this data, but will.  Note, we cannot delete newfields from the cloud until the code change catches up.

**Comment by AndrewVSutherland** [comment]
Done.  I trust it is safe to delete fields.old?

**Comment by jwj61** [comment]
Yes.
