### ISSUE TITLE
Pull request for bmfs and ecnf

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb-inventory#53]
Please could we copy the following to the cloud?
1. elliptic_curves.nfcurves with rand and stats
2. bmfs.dimensions, bmfs.forms, bmfs.forms.rand
The bmfs database does not yet exist on the cloud.

It may be that we do not yet need to copy bmfs to the cloud since the code which refers to it is all beta but I think it would be safer to do so now: after the next push master -> prod  anyone looking at an elliptic curve over an imaginary quadratic field will see a link to a Bianchi modular form but that will surely not work if the data is not there.  (I should perhaps make those links not appear except in beta mode -- let me know if that is the case!)

**Comment by AndrewVSutherland** [comment]
1 and 2 are both done.  Let me know if you are happy with nfcurves so I can delete the old versions.

**Comment by JohnCremona** [comment]
Thanks -- it may not be until tomorrow (likewise your other PR -- I was not expecting it so fast!)

**Comment by JohnCremona** [comment]
OK -- looks good, you can delete the nfcurves*old collections (or I will if you are too busy celebrating!)

**Comment by AndrewVSutherland** [comment]
Done (celebrating will commence shortly :))

**Comment by JohnCremona** [comment]
Same again please (both bmfs and nfcurves, same collections as before).
This adds data over 2.0.3.1 for range 120k-130k (both bmfs and nfcurves); adds some missing cm curves; and adds galrep data to all the nfcurves.

**Comment by AndrewVSutherland** [comment]
Done.  Let me know once you have checked the results and I will delete the old versions.

**Comment by JohnCremona** [comment]
Looks good, the old ones can go.  e.g. see the large exceptional prime at EllipticCurve/2.0.3.1/109561.1/CMa/1.  Thanks!

**Comment by JohnCremona** [comment]
Same again would add data for field 2.0.3.1 range 130k-140k for both Bianchi forms and elliptic curves.  In a week or so there will be more so it's fine to ignore this -- not bug fixes, just more date.

**Comment by AndrewVSutherland** [comment]
Done!

**Comment by JohnCremona** [comment]
Thanks a lot

**Comment by JohnCremona** [comment]
On 2017-08-03 I updated bmfs.{forms,dimensions} and elliptic_curves.nfcurves myself.

Just adding this to keep the record up-to-date -- possibly not neccessary?

**Comment by AndrewVSutherland** [comment]
@JohnCremona I think this is useful.  When I get a chance I will modify the update script to log information in a mongo db collection, but I have not done this yet.
