### ISSUE TITLE
pull request for number fields

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb-inventory#58]
Please pull numberfields.fields and numberfields.fields.rand to the cloud

Changes are: polynomials now use the new polredabs, we have a field so we can search for the old polredabs polynomials (code already in the production server), and new fields added (mostly from Weil polynomials)

**Comment by AndrewVSutherland** [comment]
Done -- let me know if everything looks ok and then I will delete the old versions.

**Comment by jwj61** [comment]
Go ahead and delete old versions.
