### ISSUE TITLE
pull request for local fields

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb-inventory#59]
Please pull localfields.fields to the cloud.  Change is the inclusion of Global Splitting Models for more fields.

**Comment by AndrewVSutherland** [comment]
Done -- let me know if everything looks ok and then I will delete the old versions.

**Comment by jwj61** [comment]
Something isn't right.

  http://beta.lmfdb.org/LocalNumberField/151.13.0.1

shows a Galois splitting model, but

  http://www.lmfdb.org/LocalNumberField/151.13.0.1

says it is not computed.

**Comment by AndrewVSutherland** [comment]
Can you take a look again now?

**Comment by jwj61** [comment]
Now it works, thanks.

**Comment by AndrewVSutherland** [comment]
Among the collections fields (15516) · fields.old (5321) · fields.rand (15516) · fields.tmp (15516) · newfields (15516) · newfields.rand (15516) currently listed on http://www.lmfdb.org/api/all, is it now safe to get rid of everything except fields and fields.rand, or do we still need newfields and newfields.rand?

**Comment by jwj61** [comment]
Keep just fields and fields.rand

**Comment by AndrewVSutherland** [comment]
Done.   I would suggest also cleaning up the localfields database on beta if it is appropriate to do so, but I'll leave that to you.
