### ISSUE TITLE
genus2_curves.tamagawa_numbers

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb-inventory#60]
This collection has no description and also has no indexes, which makes most of the queries quite slow.

I believe we only need to add a compound index on label and p.

Here are some queries that pop up in the log when we run the tests on the genus 2 curves directory.
https://gist.github.com/4ed84c4523792a4c324978361c9786de

**Comment by AndrewVSutherland** [comment]
Index has been added to both beta and prod (page load times are now 150-200ms faster, good catch).

**Comment by edgarcosta** [comment]
Thanks

**Comment by AndrewVSutherland** [comment]
I also added a description of the tamagawa_number collection to the genus2_curves inventory.

**Comment by edgarcosta** [comment]
Great. 
Thank you very much
