### ISSUE TITLE
Pull request for local fields

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb-inventory#75]
Not needed immediately, but before the current master makes it to production, we should update

 fields
 fields.rand

from the database localfields.  There is a new entry and index.

**Comment by AndrewVSutherland** [comment]
Done.  Let me know if everything looks OK and I'll delete the old versions.

**Comment by jwj61** [comment]
Looks ok.

**Comment by AndrewVSutherland** [comment]
Thanks, old versions are gone.
