### ISSUE TITLE
Update artin representations in cloud

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb-inventory#76]
The collections
artin.field_data
artin.representations
artin.representations.rand

are ready to be updated to the cloud.  The main change is that polynomials are now use the new polredabs version, but it also contains some new fields/representations.

**Comment by AndrewVSutherland** [comment]
Done.  Let me know if everything looks OK and I will then delete the old versions.

**Comment by jwj61** [comment]
Looks good.  Go ahead and delete old versions.
