### ISSUE TITLE
Data pull request for number fields

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb-inventory#79]
Please upload

numberfields.fields
numberfields.fields.rand
numberfields.stats

to the cloud.

The main change is that this contains the latest (and possibly last) attempt to fill in class group information.  It also adds two octic fields suggested through the feedback page which allow us to increase the completeness claim for one signature, and two septic fields ramified at two smallish primes.

**Comment by AndrewVSutherland** [comment]
I'll do this now.

**Comment by jwj61** [comment]
Thanks.  I see that the data is there including the statistics, but when I run a search on www.lmfdb.org and on beta, the one on beta completes quickly and the one on the main site times out.  Does it still have to build indexes?

http://beta.lmfdb.org/NumberField/?start=0&degree=8&signature=%5B0%2C4%5D&count=20
http://www.lmfdb.org/NumberField/?start=0&degree=8&signature=%5B0%2C4%5D&count=20

**Comment by AndrewVSutherland** [comment]
I had switched www.lmfdb.org to read from the mirror while the update was in progress and just now switched it back to reading from ms, where the updated files should now be available.  The query seems to run quickly now, but can you check the data again (what you were looking at before was just a mirror of beta).

**Comment by jwj61** [comment]
I see.  

This does not seem to have the new data.  Degree 7 ramified at exactly 2,73 should now have 10 fields rather than 8, and the total number of fields is different between main and beta.

**Comment by AndrewVSutherland** [comment]
OK, I'll need to look more closely to see what went wrong with the update.  I'm traveling at the moment so this likely won't happen until tomorrow.

**Comment by jwj61** [comment]
No problem.

**Comment by JohnCremona** [comment]
When I have done an update on any elliptic curve or ecnf or bianchi data I have not done the redirect which you (@AndrewVSutherland ) mentioned.  Do you do that because the number fields collection is a lot larger?  (Going by the dump size, number_fields is 39G while elliptic_curves is only 2.1G so that would make sense.)

**Comment by AndrewVSutherland** [comment]
@JohnCremona Yes, for small updates I don't think this is necessary.  The LMFDB may slow to respond while it builds indexes, but if this only takes a few minutes, no big deal.  But for numberfields/fields it takes a couple of hours (BTW, the dump size is less relevant than the number of records and the number of indexes (and their complexity)).

**Comment by AndrewVSutherland** [comment]
@jwj61 OK, the new data should be visible now (it hit a name conflict during renaming because of existing .old fields left over from the last update).

Can you check the data again and let me know if all is well (I will then delete the .old versions).

**Comment by jwj61** [comment]
Looks good.  Go ahead and delete old versions.

**Comment by JohnCremona** [comment]
So yet another addition to the script https://github.com/edgarcosta/lmfdb-gce/blob/master/db_scripts/update-cloud-db.sh (I am good at suggesting work for others!) would be to test if there are already any *.old collections present, and if so bail out with a warning, doing nothing.
