### ISSUE TITLE
number field pull request

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb-inventory#82]
Please copy the following to the cloud:

numberfields.fields
numberfields.fields.rand
numberfields.stats

This adds a bunch of trinomials (in response to a comment through the feedback page), several PGL(2,7) octics (which are now mentioned in a paper by J&R), and fills in optional data for more fields.

**Comment by JohnCremona** [comment]
I could do this but would rather not start now (9pm UK) as I think it takes a while and I would want to be around when it finishes.  If no-one else has already, I can do it Wednesday morning.

**Comment by jwj61** [comment]
No hurry, and yes, it takes hours to build the indexes.

**Comment by AndrewVSutherland** [comment]
I just kicked this off.  I switched the production server to read from m0 so the index builds won't disrupt anything.  Once all the indexes are built I will switch it back and let you know (might be tomorrow morning, depending on how long it takes).

**Comment by AndrewVSutherland** [comment]
The data should now be available on www.lmfdb.org, let me know if everything looks good and I will delete the old files.

**Comment by JohnCremona** [comment]
Thanks @AndrewVSutherland -- switching which db the production servers reads from is definitely above my pay grade.

**Comment by jwj61** [comment]
Looks good.  Go ahead and drop old files.

**Comment by AndrewVSutherland** [comment]
Done, thanks.
