### ISSUE TITLE
Pull request for number fields

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb-inventory#83]
numberfields.fields has been updated to remove the two keys related to the old version of polredabs, as has the index for them.  Also, more empty values (such as [] or {}) have been entered for optional keys where there was no data before to make the set of keys per entry more uniform.  There is no rush on this since none of it affects the end user.

**Comment by JohnCremona** [comment]
OK, I'll do an inventory rescrape so that is visible there, and we'll need to "copy to the cloud" too.  I seem to remember that takes a while for this collection, so might best be done overnight.

**Comment by JohnCremona** [comment]
Do the pages http://beta.lmfdb.org/inventory/numberfields/fields/ and http://beta.lmfdb.org/inventory/numberfields/fields/records/ look right to you?  Much tidier.

**Comment by AndrewVSutherland** [comment]
I can take care of copying this to the cloud (I'll switch www.lmfdb.org to read from the mirror so there should be no impact on users).

**Comment by jwj61** [comment]
For @JohnCremona, the .../records looks right.  I will need to go back and look again at .../fields.
