### ISSUE TITLE
Artin representation pull request

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb-inventory#84]
This is a pull request for artin representations:
 artin.field_data
 artin.representations
 artin.representations.rand

There is new data, all of small conductor, including some 2-dimensional representations for a project by Booker, et. al.

**Comment by AndrewVSutherland** [comment]
Done.  Let me know if everything looks good and I will remove the old versions.

**Comment by jwj61** [comment]
Looks good
